name: deploy-scf

on:
  push:
    branches:
      - master
  workflow_dispatch: # 手动触发

jobs:
  scf-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - name: copy env to .env.production
        run: |
          cat .envProd-GZ > .env.production
          
      - name: Login to sit Tencent Cloud Registry 
        uses: docker/login-action@v2
        with:
          registry: gocyber-sh.tencentcloudcr.com
          username: ${{ secrets.TENCENT_DOCKER_USERNAME }}
          password: ${{ secrets.TENCENT_DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push docker image 
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: dockerfile.sit  //按设置打包并推送镜像
          tags: gocyber-sh.tencentcloudcr.com/gocyber-fe/dashboard:${{ github.sha }}
 
      - name: Set up serverless  
        run: npm install -g serverless

      - name: Deploy to Tencent 
        run: |
          serverless deploy --stage production
        env:
          SERVERLESS_PLATFORM_VENDOR: tencent #serverless 境外默认为 aws，配置为腾讯
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }} #您的腾讯云账号 sercret ID
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }} #您的腾讯云账号 sercret key
          DOCKER_IMAGE_TAG: ${{ github.sha }} #镜像版本号
          SCF_NAME: dab
          MEMORY_SIZE: 512